name: stylometry
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - plotly
  - networkx
  - panel
  - holoviews
  - bokeh
  - matplotlib
  - pip
  - pip:
    - tabulator
